version: 0.2

phases:
pre_build:
commands:
- echo Logging into Amazon ECR
- aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 408032760208.dkr.ecr.ap-south-1.amazonaws.com
- COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
- IMAGE_TAG=$COMMIT_ID
- echo Image tag is $IMAGE_TAG

build:
commands:
- echo Building Docker image
- docker build -t avs-frontend:$IMAGE_TAG .
- docker tag avs-frontend:$IMAGE_TAG 408032760208.dkr.ecr.ap-south-1.amazonaws.com/avs-frontend:$IMAGE_TAG

post_build:
commands:
- echo Pushing Docker image
- docker push 408032760208.dkr.ecr.ap-south-1.amazonaws.com/avs-frontend:$IMAGE_TAG
- printf '[{"name":"frontend","imageUri":"%s"}]' 408032760208.dkr.ecr.ap-south-1.amazonaws.com/avs-frontend:$IMAGE_TAG > imagedefinitions.json

artifacts:
files:
- imagedefinitions.json
